### ISSUE TITLE
Saving SchoolDataService.tt won't build .cs file

### ISSUE THREAD

**Issue by shiemstra01** [ProCodersPtyLtd/MasterDetailsDataEntry#105]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shiemstra01** [comment]
I am missing something. The name spaces for Platz.SqlForms aren't picking up; and the transformation gives the error "'u' is an invalid start of a value."  So I can't run the code generator.

Otherwise, WOW! This is the package I have been looking for.  Thank you for a terrific effort.  Looking for more as you are able.

**Comment by euklad** [comment]
You're right, the template doesn't contain one namespace, I will fix it in next release.
As a workaround please add the following import to the header of SchoolDataService.tt:
<#@ import namespace="Platz.SqlForms" #>
